# Generated by Django 5.2.4 on 2025-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('story', models.TextField(default='Our story...')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('values', models.TextField(default='Innovation:We constantly push the boundaries of design to create unique, innovative solutions for our clients.;Passion:Our passion for design drives us to deliver exceptional results that exceed expectations.;Collaboration:We work closely with our clients to ensure their vision becomes reality.;Excellence:We strive for excellence in every project, no matter how big or small.', help_text='Format: Title:Description;Title:Description;...')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
